# Generated by Django 5.0.6 on 2024-08-03 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='ویژیگی')),
                ('deleted', models.BooleanField()),
                ('is_activated', models.BooleanField()),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ویژیگی',
                'verbose_name_plural': ' ویژیگیها',
            },
        ),
        migrations.CreateModel(
            name='BaseProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('category', models.CharField(max_length=50, verbose_name='دسته\u200cبندی')),
                ('deleted', models.BooleanField()),
                ('is_activated', models.BooleanField()),
            ],
            options={
                'verbose_name': 'محصول پایه',
                'verbose_name_plural': 'محصولات پایه',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='مقدار')),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.attributes', verbose_name='ویژگی')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.baseproducts', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مقدار',
                'verbose_name_plural': 'مقادیر',
            },
        ),
    ]
