# Generated by Django 5.0.6 on 2024-08-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproducts',
            name='img',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
