# Generated by Django 5.0.6 on 2024-08-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_baseproducts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproducts',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیحات'),
        ),
    ]
