# Generated by Django 5.0.6 on 2024-08-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_baseproducts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproducts',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی'),
        ),
    ]
