# Generated by Django 5.0.6 on 2024-08-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_baseproducts_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproducts',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت محصول'),
        ),
    ]
