# Generated by Django 5.0.6 on 2024-11-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_baseproducts_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'دسته یندی',
                'verbose_name_plural': 'دسته یندی ها',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='baseproducts',
            name='category',
        ),
    ]
