# Generated by Django 5.0.6 on 2024-11-27 09:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_baseproducts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproducts',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
