# Generated by Django 5.0.6 on 2024-11-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_baseproducts_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproducts',
            name='color',
        ),
    ]
