# Generated by Django 5.0.6 on 2024-11-27 09:28

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_baseproducts_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='colors',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
