# Generated by Django 5.0.6 on 2024-11-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_value_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.CharField(max_length=200, null=True, verbose_name='مقدار'),
        ),
    ]
