# Generated by Django 5.0.6 on 2024-11-27 11:11

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_value_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='colors',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='مقدار'),
        ),
    ]
