# Generated by Django 5.0.6 on 2024-09-17 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0008_alter_baseproducts_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='جمع قیمت')),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.baseproducts', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
    ]
